"""
routers/analysis.py — Algorithm Debugger API

Serves analysis.json files generated by the clipping pipeline.
All routes are under /dev/ prefix — internal developer tool only.
Restricted via ENABLE_DEBUGGER configuration settings.
"""
from __future__ import annotations

import json
import logging
import os
import tempfile
import uuid
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, JSONResponse

import config

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/dev", tags=["Algorithm Debugger"])


def _check_debugger_enabled():
    """Raise 403 Forbidden if debugger features are disabled in configuration."""
    if not config.ENABLE_DEBUGGER:
        raise HTTPException(
            status_code=403,
            detail="Debugger endpoint access is disabled in production."
        )

def _validate_uuid(run_uuid: str) -> None:
    """Validate that run_uuid is a valid UUID to prevent path traversal."""
    try:
        uuid.UUID(run_uuid)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail="Invalid run_uuid format.") from exc

def _get_outputs_dir() -> Path:
    """Return the outputs directory, respecting Vercel environment."""
    if os.environ.get("VERCEL"):
        return Path(tempfile.gettempdir()) / "clippods_outputs"
    return config.OUTPUTS_DIR


def _find_analysis_files() -> list[dict]:
    """Scan outputs/ for all analysis.json files and return summary info."""
    outputs_dir = _get_outputs_dir()
    if not outputs_dir.exists():
        return []

    results = []
    for run_dir in sorted(outputs_dir.iterdir(), reverse=True):
        if not run_dir.is_dir():
            continue
        
        # Validate that directory name is a valid UUID
        try:
            uuid.UUID(run_dir.name)
        except ValueError:
            continue # ignore non-UUID outputs directories

        analysis_path = run_dir / "analysis.json"
        if not analysis_path.exists():
            continue

        try:
            data = json.loads(analysis_path.read_text(encoding="utf-8"))
            meta = data.get("meta", {})
            stats = data.get("stats", {})
            results.append({
                "run_uuid": run_dir.name,
                "job_id": meta.get("job_id"),
                "filename": meta.get("filename", "unknown"),
                "source": meta.get("source", "unknown"),
                "video_duration_seconds": meta.get("video_duration_seconds"),
                "timestamp": meta.get("timestamp"),
                "algorithm_version": meta.get("algorithm_version"),
                "clips_count": len(data.get("final_clips", [])),
                "candidates_count": stats.get("total_candidates", 0),
            })
        except Exception as exc:
            logger.warning("Failed to read analysis.json in %s: %s", run_dir, exc)
            continue

    return results


def _load_analysis(run_uuid: str) -> Optional[dict]:
    """Load and return analysis.json for a given run_uuid."""
    _validate_uuid(run_uuid)
    outputs_dir = _get_outputs_dir()
    analysis_path = outputs_dir / run_uuid / "analysis.json"
    if not analysis_path.exists():
        return None
    try:
        return json.loads(analysis_path.read_text(encoding="utf-8"))
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/analysis/jobs")
async def list_analysis_jobs():
    """List all processed jobs that have analysis.json files."""
    _check_debugger_enabled()
    jobs = _find_analysis_files()
    return {"jobs": jobs, "count": len(jobs)}


@router.get("/analysis/{run_uuid}")
async def get_analysis(run_uuid: str):
    """Return the full analysis.json for a specific run."""
    _check_debugger_enabled()
    _validate_uuid(run_uuid)
    data = _load_analysis(run_uuid)
    if data is None:
        raise HTTPException(status_code=404, detail=f"No analysis found for run {run_uuid}")
    return data


@router.get("/analysis/{run_uuid}/summary")
async def get_analysis_summary(run_uuid: str):
    """Return only meta + stats (lightweight) for a specific run."""
    _check_debugger_enabled()
    _validate_uuid(run_uuid)
    data = _load_analysis(run_uuid)
    if data is None:
        raise HTTPException(status_code=404, detail=f"No analysis found for run {run_uuid}")
    return {
        "meta": data.get("meta", {}),
        "stats": data.get("stats", {}),
        "final_clips_count": len(data.get("final_clips", [])),
    }


# ---------------------------------------------------------------------------
# Video serving for debugger playback
# ---------------------------------------------------------------------------

@router.get("/video/{run_uuid}")
async def serve_original_video(run_uuid: str):
    """Serve the original video file for debugger playback."""
    _check_debugger_enabled()
    _validate_uuid(run_uuid)
    outputs_dir = _get_outputs_dir()
    run_dir = outputs_dir / run_uuid

    if not run_dir.exists():
        raise HTTPException(status_code=404, detail="Run directory not found")

    # Look for original.* file
    for f in run_dir.iterdir():
        if f.name.startswith("original") and f.is_file():
            return FileResponse(
                str(f),
                media_type="video/mp4",
                headers={"Accept-Ranges": "bytes"},
            )

    raise HTTPException(
        status_code=404,
        detail="Original video not found. Set KEEP_ORIGINAL_FOR_DEBUG=true to enable.",
    )
