import React, { useState } from "react";
import { formatTime } from "../utils/format";
import { HeuristicBreakdown, ExecutionTrace, VideoSeekPlayer } from "./common";
import { getVideoUrl } from "../api/analysis";

export default function CandidateExplorer({
  analysisData,
  compareA,
  compareB,
  setCompareA,
  setCompareB,
  showComparison,
  setShowComparison
}) {
  const [selectedCandidate, setSelectedCandidate] = useState(null);
  const [sortField, setSortField] = useState("id");
  const [sortOrder, setSortOrder] = useState("asc");
  const [filterStatus, setFilterStatus] = useState("all");

  if (!analysisData) {
    return <div className="empty-message">No candidates data available. Please select a job.</div>;
  }

  const { candidates, meta } = analysisData;

  // Handle Sort
  const handleSort = (field) => {
    if (sortField === field) {
      setSortOrder(sortOrder === "asc" ? "desc" : "asc");
    } else {
      setSortField(field);
      setSortOrder("asc");
    }
  };

  const getSortedCandidates = () => {
    const list = [...(candidates || [])];
    
    // Apply filter first
    const filteredList = list.filter(c => {
      if (filterStatus === "selected") return c.selected;
      if (filterStatus === "rejected") return !c.selected;
      return true;
    });

    return filteredList.sort((a, b) => {
      let valA, valB;
      if (sortField === "raw_score" || sortField === "word_density" || sortField === "speech_ratio") {
        valA = a.metrics?.[sortField] ?? 0;
        valB = b.metrics?.[sortField] ?? 0;
      } else if (sortField === "stop_score") {
        valA = a.end_analysis?.total_score ?? 0;
        valB = b.end_analysis?.total_score ?? 0;
      } else {
        valA = a[sortField];
        valB = b[sortField];
      }

      if (valA < valB) return sortOrder === "asc" ? -1 : 1;
      if (valA > valB) return sortOrder === "asc" ? 1 : -1;
      return 0;
    });
  };

  const sortedCandidates = getSortedCandidates();

  return (
    <div className="candidate-explorer-tab">
      {/* Tab Navigation header */}
      <div className="candidate-tab-header">
        <div className="header-info">
          <h3>Algorithm Candidate Explorer</h3>
          <p className="subtitle">Inspect every candidate segment generated by the sliding window, analyze rejections, or compare side-by-side.</p>
        </div>
        <div className="header-actions">
          <button
            className={`btn ${showComparison ? "btn-primary" : "btn-outline"}`}
            onClick={() => setShowComparison(!showComparison)}
          >
            {showComparison ? "Show Table Explorer" : "Open Comparison Mode"}
          </button>
        </div>
      </div>

      {showComparison ? (
        <CandidateComparison
          candidates={candidates}
          compareA={compareA}
          compareB={compareB}
          setCompareA={setCompareA}
          setCompareB={setCompareB}
          runUuid={meta.run_uuid}
        />
      ) : (
        <div className="explorer-grid">
          {/* Main Table Card */}
          <div className="card table-card">
            <div className="card-header table-filters">
              <div className="filter-group">
                <label>Filter Status:</label>
                <select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)}>
                  <option value="all">All Candidates</option>
                  <option value="selected">Selected Clips Only</option>
                  <option value="rejected">Rejected Only</option>
                </select>
              </div>
              <div className="table-stats-summary">
                Showing <strong>{sortedCandidates.length}</strong> candidates
              </div>
            </div>
            <div className="card-body scroll-table-container">
              <table className="candidate-table">
                <thead>
                  <tr>
                    <th onClick={() => handleSort("id")}>ID {sortField === "id" && (sortOrder === "asc" ? "▲" : "▼")}</th>
                    <th onClick={() => handleSort("window_start")}>Start {sortField === "window_start" && (sortOrder === "asc" ? "▲" : "▼")}</th>
                    <th onClick={() => handleSort("window_end")}>End {sortField === "window_end" && (sortOrder === "asc" ? "▲" : "▼")}</th>
                    <th onClick={() => handleSort("duration")}>Duration {sortField === "duration" && (sortOrder === "asc" ? "▲" : "▼")}</th>
                    <th onClick={() => handleSort("raw_score")}>Density Score {sortField === "raw_score" && (sortOrder === "asc" ? "▲" : "▼")}</th>
                    <th onClick={() => handleSort("stop_score")}>Stop Score {sortField === "stop_score" && (sortOrder === "asc" ? "▲" : "▼")}</th>
                    <th onClick={() => handleSort("speech_ratio")}>Speech % {sortField === "speech_ratio" && (sortOrder === "asc" ? "▲" : "▼")}</th>
                    <th>Status</th>
                    <th>Rejection Reason</th>
                  </tr>
                </thead>
                <tbody>
                  {sortedCandidates.map((c) => (
                    <tr
                      key={c.id}
                      className={`candidate-row-item ${selectedCandidate?.id === c.id ? "row-selected" : ""} ${c.selected ? "row-is-selected-clip" : ""}`}
                      onClick={() => setSelectedCandidate(c)}
                    >
                      <td>#{c.id}</td>
                      <td>{formatTime(c.window_start)}</td>
                      <td>{formatTime(c.window_end)}</td>
                      <td>{c.duration}s</td>
                      <td>{c.metrics?.raw_score || "N/A"}</td>
                      <td>{c.end_analysis?.total_score || "N/A"}/8</td>
                      <td>{c.metrics?.speech_ratio ? `${Math.round(c.metrics.speech_ratio * 100)}%` : "N/A"}</td>
                      <td>
                        <span className={`badge ${c.selected ? "badge-success" : "badge-danger"}`}>
                          {c.selected ? "SELECTED" : "REJECTED"}
                        </span>
                      </td>
                      <td className="rejection-text">{c.rejection_reason ? c.rejection_reason.replace(/_/g, " ") : "—"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Details Sidebar */}
          {selectedCandidate ? (
            <CandidateDetailPanel
              candidate={selectedCandidate}
              runUuid={meta.run_uuid}
              onCompareSelect={(type) => {
                if (type === "A") setCompareA(selectedCandidate.id);
                if (type === "B") setCompareB(selectedCandidate.id);
                setShowComparison(true);
              }}
            />
          ) : (
            <div className="card detail-placeholder-card">
              <p>Click on any candidate row in the table to inspect its full execution trace, start/end heuristic analysis, stopping points details, and play the original video context.</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function CandidateDetailPanel({ candidate, runUuid, onCompareSelect }) {
  const [activeSubTab, setActiveSubTab] = useState("trace");

  return (
    <div className="card candidate-detail-sidebar">
      <div className="card-header detail-sidebar-header">
        <div className="header-meta">
          <span className={`badge ${candidate.selected ? "badge-success" : "badge-danger"}`}>
            {candidate.selected ? "SELECTED" : "REJECTED"}
          </span>
          <h4>Candidate Window #{candidate.id}</h4>
        </div>
        <div className="sidebar-compare-actions">
          <button className="btn btn-sm btn-outline" onClick={() => onCompareSelect("A")}>Set as A</button>
          <button className="btn btn-sm btn-outline" onClick={() => onCompareSelect("B")}>Set as B</button>
        </div>
      </div>
      <div className="card-body no-padding scroll-sidebar-body">
        {/* Inner sub-tabs */}
        <div className="sub-tabs-bar">
          <button className={`sub-tab ${activeSubTab === "trace" ? "sub-tab-active" : ""}`} onClick={() => setActiveSubTab("trace")}>Trace</button>
          <button className={`sub-tab ${activeSubTab === "heuristics" ? "sub-tab-active" : ""}`} onClick={() => setActiveSubTab("heuristics")}>Heuristics</button>
          <button className={`sub-tab ${activeSubTab === "stopping_points" ? "sub-tab-active" : ""}`} onClick={() => setActiveSubTab("stopping_points")}>Stopping Points</button>
          <button className={`sub-tab ${activeSubTab === "playback" ? "sub-tab-active" : ""}`} onClick={() => setActiveSubTab("playback")}>Playback</button>
        </div>

        <div className="sidebar-content-padded">
          {activeSubTab === "trace" && (
            <ExecutionTrace trace={candidate.trace} />
          )}

          {activeSubTab === "heuristics" && (
            <div className="heuristics-detail-panel">
              <div className="metrics-simple-list">
                <div className="metric-row"><span>Start Time:</span><strong>{formatTime(candidate.window_start)}</strong></div>
                <div className="metric-row"><span>End Time:</span><strong>{formatTime(candidate.window_end)}</strong></div>
                <div className="metric-row"><span>Duration:</span><strong>{candidate.duration} seconds</strong></div>
                <div className="metric-row"><span>Word Density:</span><strong>{candidate.metrics?.word_density} words/sec</strong></div>
                <div className="metric-row"><span>Speech Ratio:</span><strong>{candidate.metrics?.speech_ratio ? `${Math.round(candidate.metrics.speech_ratio * 100)}%` : "N/A"}</strong></div>
              </div>

              <div className="start-checks-box">
                <h4>Start Point Checks</h4>
                <div className="start-checks-list">
                  {candidate.start_analysis?.checks.map((ch, idx) => (
                    <div key={idx} className="start-check-item">
                      <span className={`check-icon ${ch.passed ? "text-success" : "text-danger"}`}>
                        {ch.passed ? "✓" : "✗"}
                      </span>
                      <div className="check-text">
                        <strong>{ch.name.replace(/_/g, " ")}:</strong> {ch.detail}
                        {ch.actual_seconds !== undefined && <div className="check-sub">Actual: {ch.actual_seconds}s</div>}
                        {ch.actual !== undefined && <div className="check-sub">Actual: {ch.actual}</div>}
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <HeuristicBreakdown
                scoreBreakdown={candidate.end_analysis?.score_breakdown}
                totalScore={candidate.end_analysis?.total_score}
              />
            </div>
          )}

          {activeSubTab === "stopping_points" && (
            <StoppingPointExplorer stoppingPoints={candidate.stopping_points} />
          )}

          {activeSubTab === "playback" && (
            <div className="playback-panel">
              <h4>Play Original Video</h4>
              <VideoSeekPlayer
                src={getVideoUrl(runUuid)}
                start={candidate.window_start}
                end={candidate.window_end}
                runUuid={runUuid}
              />
              <div className="transcript-preview-box">
                <h5>Transcript Preview</h5>
                <p>"{candidate.start_analysis?.transcript_preview || "No transcript preview"}"</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function StoppingPointExplorer({ stoppingPoints }) {
  return (
    <div className="stopping-points-explorer">
      <h4>Evaluated Stopping Points ({stoppingPoints?.length || 0})</h4>
      <p className="subtitle">The algorithm evaluates every potential word/sentence boundary. The one with the highest stopping score is selected.</p>
      
      <div className="stopping-points-list">
        {stoppingPoints && stoppingPoints.map((sp, idx) => (
          <div key={idx} className={`stopping-point-card ${sp.selected ? "sp-is-selected" : ""}`}>
            <div className="sp-card-header">
              <span className="sp-timestamp">Timestamp: <strong>{formatTime(sp.timestamp)}</strong></span>
              <span className="sp-score-badge">Score: <strong>{sp.total_score} / 8</strong></span>
              {sp.selected && <span className="sp-winner-badge">WINNER</span>}
            </div>
            <div className="sp-card-body">
              <div className="sp-mini-row">Duration if ended here: {sp.clip_duration_at_point}s</div>
              <div className="sp-heuristics-grid">
                {sp.score_breakdown?.map((hb, hidx) => (
                  <div key={hidx} className={`sp-h-item ${hb.passed ? "sp-h-passed" : "sp-h-failed"}`}>
                    <span className="sp-h-dot"></span>
                    <span className="sp-h-name">{hb.heuristic.replace(/_/g, " ")}: +{hb.points}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function CandidateComparison({ candidates, compareA, compareB, setCompareA, setCompareB, runUuid }) {
  const candA = candidates?.find(c => c.id === compareA);
  const candB = candidates?.find(c => c.id === compareB);

  const getDelta = (valA, valB) => {
    if (valA === undefined || valB === undefined) return "";
    const diff = valA - valB;
    if (diff === 0) return "0";
    return diff > 0 ? `+${diff.toFixed(2)}` : `${diff.toFixed(2)}`;
  };

  const getDeltaClass = (valA, valB, lowerIsBetter = false) => {
    if (valA === undefined || valB === undefined) return "";
    const diff = valA - valB;
    if (diff === 0) return "delta-equal";
    const positiveIsGood = !lowerIsBetter;
    if (diff > 0) return positiveIsGood ? "delta-better" : "delta-worse";
    return positiveIsGood ? "delta-worse" : "delta-better";
  };

  return (
    <div className="candidate-comparison-container">
      <div className="card comparison-selectors-card">
        <div className="selectors-row">
          <div className="selector-field">
            <label>Compare Candidate A:</label>
            <select value={compareA || ""} onChange={(e) => setCompareA(Number(e.target.value))}>
              <option value="">Select Candidate A</option>
              {candidates?.map(c => (
                <option key={c.id} value={c.id}>Candidate #{c.id} ({c.selected ? "Clip" : "Rejected"})</option>
              ))}
            </select>
          </div>
          <div className="comparison-vs">VS</div>
          <div className="selector-field">
            <label>Compare Candidate B:</label>
            <select value={compareB || ""} onChange={(e) => setCompareB(Number(e.target.value))}>
              <option value="">Select Candidate B</option>
              {candidates?.map(c => (
                <option key={c.id} value={c.id}>Candidate #{c.id} ({c.selected ? "Clip" : "Rejected"})</option>
              ))}
            </select>
          </div>
        </div>
      </div>

      <div className="comparison-cols-grid">
        {/* Candidate A Column */}
        <div className="card comparison-col-card">
          <div className="card-header comparison-col-header" style={{ borderTop: candA?.selected ? "4px solid var(--success)" : "4px solid var(--danger)" }}>
            <h3>Candidate A: #{candA?.id ?? "None"}</h3>
            <span className={`badge ${candA?.selected ? "badge-success" : "badge-danger"}`}>
              {candA ? (candA.selected ? "SELECTED CLIP" : "REJECTED WINDOW") : "N/A"}
            </span>
          </div>
          {candA ? (
            <div className="card-body">
              <div className="comparison-metrics-list">
                <div className="comp-m-row"><span>Start Time:</span> <strong>{formatTime(candA.window_start)}</strong></div>
                <div className="comp-m-row"><span>End Time:</span> <strong>{formatTime(candA.window_end)}</strong></div>
                <div className="comp-m-row"><span>Duration:</span> <strong>{candA.duration}s</strong></div>
                <div className="comp-m-row"><span>Word Density:</span> <strong>{candA.metrics?.word_density} w/s</strong></div>
                <div className="comp-m-row"><span>Speech Ratio:</span> <strong>{Math.round((candA.metrics?.speech_ratio ?? 0) * 100)}%</strong></div>
                <div className="comp-m-row"><span>Stop Score:</span> <strong>{candA.end_analysis?.total_score}/8</strong></div>
                {candA.rejection_reason && (
                  <div className="rejection-reason-box mt-10">
                    <strong>Rejection:</strong> {candA.rejection_reason.replace(/_/g, " ").toUpperCase()}
                  </div>
                )}
              </div>
              <div className="video-column-player-box">
                <VideoSeekPlayer src={getVideoUrl(runUuid)} start={candA.window_start} end={candA.window_end} runUuid={runUuid} />
              </div>
              <div className="start-checks-box mt-15">
                <h4>Start Quality Checks</h4>
                {candA.start_analysis?.checks.map((ch, idx) => (
                  <div key={idx} className="comp-check-item">
                    <span className={ch.passed ? "text-success" : "text-danger"}>{ch.passed ? "✓" : "✗"}</span>
                    <span>{ch.name.replace(/_/g, " ")}</span>
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div className="card-body empty-message">Select Candidate A from the dropdown above.</div>
          )}
        </div>

        {/* Delta / Comparison Metrics Column */}
        {candA && candB && (
          <div className="card comparison-delta-card">
            <div className="card-header comparison-col-header">
              <h3>Metric Deltas</h3>
              <span className="badge badge-neutral">A vs B</span>
            </div>
            <div className="card-body flex-col justify-center">
              <div className="delta-stats-list">
                <div className="delta-stat-row">
                  <span>Score Delta:</span>
                  <strong className={getDeltaClass(candA.metrics?.raw_score, candB.metrics?.raw_score)}>
                    {getDelta(candA.metrics?.raw_score, candB.metrics?.raw_score)}
                  </strong>
                </div>
                <div className="delta-stat-row">
                  <span>Duration Delta:</span>
                  <strong className={getDeltaClass(candA.duration, candB.duration)}>
                    {getDelta(candA.duration, candB.duration)}s
                  </strong>
                </div>
                <div className="delta-stat-row">
                  <span>Speech Ratio Delta:</span>
                  <strong className={getDeltaClass(candA.metrics?.speech_ratio, candB.metrics?.speech_ratio)}>
                    {candA.metrics && candB.metrics ? `${Math.round((candA.metrics.speech_ratio - candB.metrics.speech_ratio) * 100)}%` : "0%"}
                  </strong>
                </div>
                <div className="delta-stat-row">
                  <span>Stop Score Delta:</span>
                  <strong className={getDeltaClass(candA.end_analysis?.total_score, candB.end_analysis?.total_score)}>
                    {getDelta(candA.end_analysis?.total_score, candB.end_analysis?.total_score)}
                  </strong>
                </div>
              </div>

              <div className="comparison-verdict-box">
                <h5>Decision Verdict</h5>
                {candA.selected && !candB.selected ? (
                  <p><strong>Candidate A was selected over Candidate B.</strong> Reason: Candidate A fits the duration requirements and had a higher score or did not overlap with higher-ranking clips.</p>
                ) : !candA.selected && candB.selected ? (
                  <p><strong>Candidate B was selected over Candidate A.</strong> Reason: Candidate B was ranked higher, or Candidate A had an overlap rejection conflict.</p>
                ) : candA.selected && candB.selected ? (
                  <p>Both candidates were selected for final clip segments.</p>
                ) : (
                  <p>Both candidates were rejected due to overlaps or scores falling below the selection threshold.</p>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Candidate B Column */}
        <div className="card comparison-col-card">
          <div className="card-header comparison-col-header" style={{ borderTop: candB?.selected ? "4px solid var(--success)" : "4px solid var(--danger)" }}>
            <h3>Candidate B: #{candB?.id ?? "None"}</h3>
            <span className={`badge ${candB?.selected ? "badge-success" : "badge-danger"}`}>
              {candB ? (candB.selected ? "SELECTED CLIP" : "REJECTED WINDOW") : "N/A"}
            </span>
          </div>
          {candB ? (
            <div className="card-body">
              <div className="comparison-metrics-list">
                <div className="comp-m-row"><span>Start Time:</span> <strong>{formatTime(candB.window_start)}</strong></div>
                <div className="comp-m-row"><span>End Time:</span> <strong>{formatTime(candB.window_end)}</strong></div>
                <div className="comp-m-row"><span>Duration:</span> <strong>{candB.duration}s</strong></div>
                <div className="comp-m-row"><span>Word Density:</span> <strong>{candB.metrics?.word_density} w/s</strong></div>
                <div className="comp-m-row"><span>Speech Ratio:</span> <strong>{Math.round((candB.metrics?.speech_ratio ?? 0) * 100)}%</strong></div>
                <div className="comp-m-row"><span>Stop Score:</span> <strong>{candB.end_analysis?.total_score}/8</strong></div>
                {candB.rejection_reason && (
                  <div className="rejection-reason-box mt-10">
                    <strong>Rejection:</strong> {candB.rejection_reason.replace(/_/g, " ").toUpperCase()}
                  </div>
                )}
              </div>
              <div className="video-column-player-box">
                <VideoSeekPlayer src={getVideoUrl(runUuid)} start={candB.window_start} end={candB.window_end} runUuid={runUuid} />
              </div>
              <div className="start-checks-box mt-15">
                <h4>Start Quality Checks</h4>
                {candB.start_analysis?.checks.map((ch, idx) => (
                  <div key={idx} className="comp-check-item">
                    <span className={ch.passed ? "text-success" : "text-danger"}>{ch.passed ? "✓" : "✗"}</span>
                    <span>{ch.name.replace(/_/g, " ")}</span>
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div className="card-body empty-message">Select Candidate B from the dropdown above.</div>
          )}
        </div>
      </div>
    </div>
  );
}
